config/routes.rb
Rails.application.routes.draw do

devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }

 root 'homes#top'
 
  get "home/about" => "homes#about"
  resources :books
  resources :users, only:[:index, :show, :edit, :update]
 end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user, optional: true
  attachment :profile_image

	validates :title, presence:true
	validates :body, presence:true, length:{maximum:200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="You have creatad book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end
  
  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
       flash[:notice]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end
 
  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice]= "Book was successfully destroyed."
      redirect_to books_path
    end
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_error.html.erb
<% if model.errors.any? %>
  <div class="error">
    <h3><%= model.errors.count %> errors prohibited this obj from being saved</h3>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>

  <div class="form-title row">
    <%= f.label :Title %>
    <%= f.text_field :title, class: "col-xs-12" %>
  </div>

  <div class="form-body row">
  	<%= f.label :Opinion %>
    <%= f.text_area :body, class: "col-xs-12" %>
  </div>

  <div class="actions row">
    <%= f.submit class: "btn btn-primary col-xs-12" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h1>Editing Book</h1>
      <%= render 'layouts/error', model: @book %>
      <%= render 'books/form', book: @book %>
    <div class="menu">
      <%= link_to "Show", book_path(@book) %>
      |
      <%= link_to "Back", books_path %>
    </div>
    </div>
  <div class="col-xs-3"></div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <%= render 'layouts/error', model: @book %>
    <div class="col-xs-3">
      <%= render 'users/index', user: @user %>
      <h2>New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-xs-9">
      <table class="table book-index">
        <h2>Books</h2>
        <thead>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg"%>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/index', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'bookes/form', book: Book.new %>
    </div>

   div class="col-xs-9">
      <h1>Book detail</h1>
      <table class="table table-user-show">
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
          <td><%= link_to @user.name, user_path(@user) %></td>
          <td><%= @book.title %></td>
          <td><%= @book.body %></td>
          <% if @book.user_id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-success"%></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-danger" %></td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>