config/routes.rb
Rails.application.routes.draw do

devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }

 root 'homes#top'
 
  get "home/about" => "homes#about"
  resources :books
  resources :users, only:[:index, :show, :edit, :update]
 end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="header">
    <header class="navbar navbar-expand-log navbar-dark bg-dark" >
      <div class="container">
        <nav class="navbar-brand">
            <span class="title">Bookers</span>
        </nav>
        <nav>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="nabar-nav ml-auto">
            <% if user_signed_in? && @user == current_user %>
              <li class="">
                <%= link_to user_path(current_user) do %>
                  <i class="fas fa-home"></i>Home
                  <% end %>
              </li>
              <li class="">
                <%= link_to users_path do %>
                <i class="fas fa-users"></i>Users
                <% end %>
              </li>
              <li class="">
                <%= link_to books_path do %>
                <i class="fas fa-book-open"></i>Books
                <% end %>
              </li>
              <li class="">
                <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i>Log out
                <% end %>
              </li>
            <% else %>
              <li class="">
                <%= link_to root_path do %>
                <i class="fas fa-home">Home
                <% end %>
              </li>
              <li class="">
                <%= link_to home_about_path do %>
                <i class="fas fa-link"></i>About
                <% end %>
              </li>
              <li class="">
                <%= link_to new_user_registration_path do %>
                <i class="fas fa-user-plus"></i>Sign up
                <% end %>
              </li>
              <li class="">
                <%= link_to new_user_session_path do %>
                <i class="fa-sign-in-alt"></i>Log in
                <% end %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
  <div class="body">
      <p class="notice"><%= notice %></p>

      <%= yield %>

        <footer>
           <div class="container mt-5">
          <div class="row">
        <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
         </div>
        </div>
      </div>
    </footer>
  </body>
</html>